---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/bolaogun/my-argo-appset
      revision: develop
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/bolaogun/my-argo-appset
        targetRevision: develop
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
  - list:
      elements:
        - chartName: spark-operator
          namespace: spark-operator
          repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
          targetRevision: 1.1.26
          helmValues: ""
  template:
    metadata:
      name: '{{ chartName }}'
      namespace: argocd
    spec:
      project: default
      source:
        chart:  '{{ chartName }}'
        targetRevision: '{{ targetRevision }}'
        repoURL: '{{ repoURL }}'
        helm:
          values: '{{ helmValues }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true